### PR TITLE
Prune 2.3

### PR DESCRIPTION
**Pull request by davidkhala**
- Bump to 2.2, 2.4 to latest tags

Signed-off-by: DavidLiu <david.yx.liu@oracle.com>

### CODE REVIEW

**Comment by SamYuan1990** [comment]
@davidkhala ， CI怎么失败了？https://dev.azure.com/Hyperledger/TWGC/_build/results?buildId=48844&view=results

**Comment by davidkhala** [comment]
> @davidkhala ， CI fails？https://dev.azure.com/Hyperledger/TWGC/_build/results?buildId=48844&view=results I am not sure the reason why it fails.


I guess this is the reason
##[warning]An image label with the label Ubuntu16 does not exist.

**Comment by davidkhala** [comment]
TODO: change AZP vm pool

**Comment by davidkhala** [comment]
cancel by https://github.com/Hyperledger-TWGC/tape/commit/7b1fdafce433c0240952373cdd1c150fc614231e

**Pull request closed without merging**
