### PR TITLE
enable dependabot auto merge

### PR DESCRIPTION
**Pull request by SamYuan1990**
ref https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request to config auto merge for dependabot.
@davidkhala /@ryjones could you please help config a token for this Repo?

### CODE REVIEW

**Comment by ryjones** [comment]
@SamYuan1990 the issue is the token is not available to PRs from forks

**Comment by SamYuan1990** [comment]
> @SamYuan1990 the issue is the token is not available to PRs from forks. the token it wants is auto-generated per-run

https://github.com/Hyperledger-TWGC/tape/pull/330/files#diff-7bf85e121a1cd82112bd0cd550cbbefb951fa2b80d6cb435ed2f86d9aafb572fR17
I suppose we need to config a token in this Repo and when the action running, it will use the token configured in settings right?

**Comment by ryjones** [comment]
@SamYuan1990 no tokens are available to PRs from outside the main repo

**Comment by davidkhala** [comment]
It seems it is technically impossible. If it is the case, can I close it?

**Comment by SamYuan1990** [comment]
> It seems it is technically impossible. If it is the case, can I close it?

ok, let's close it.

**Pull request closed without merging**
